spring:
  jpa:
    hibernate:
      ddl-auto: create-drop  # ?????? ??? ?? ??/???? (create, update, validate, none ? ??)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # ???? DB? ?? Hibernate ?? ?? (??? H2)
    show-sql: true  # SQL ?? ?? ??
    generate-ddl: true  # DDL ?? ??
  datasource:
    url: jdbc:h2:mem:testdb  # H2 ??? DB? ??
    driverClassName: org.h2.Driver
    username: sa
    password:
    hikari:
      pool-name: H2
  h2:
    console:
      enabled: true  # H2 ?? ??? (?????? ?? ??)
      path: /h2-console  # ?? ?? ??